#############################################################################
# Makefile for building: bin/Text-Editor
# Generated by qmake (2.01a) (Qt 4.6.2) on: Sat Nov 13 16:12:21 2010
# Project:  Text-Editor.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Text-Editor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Ibuild
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/Editor.cpp \
		src/FileBrowser.cpp \
		src/FileBrowserView.cpp \
		src/FileTreeBrowser.cpp \
		src/main.cpp \
		src/MainWindow.cpp build/moc_Editor.cpp \
		build/moc_FileBrowser.cpp \
		build/moc_FileBrowserView.cpp \
		build/moc_FileTreeBrowser.cpp \
		build/moc_MainWindow.cpp \
		qrc_resources.cpp
OBJECTS       = build/Editor.o \
		build/FileBrowser.o \
		build/FileBrowserView.o \
		build/FileTreeBrowser.o \
		build/main.o \
		build/MainWindow.o \
		build/moc_Editor.o \
		build/moc_FileBrowser.o \
		build/moc_FileBrowserView.o \
		build/moc_FileTreeBrowser.o \
		build/moc_MainWindow.o \
		build/qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Text-Editor.pro
QMAKE_TARGET  = Text-Editor
DESTDIR       = bin/
TARGET        = bin/Text-Editor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Text-Editor.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Text-Editor.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Text-Editor.pro

dist: 
	@$(CHK_DIR_EXISTS) build/Text-Editor1.0.0 || $(MKDIR) build/Text-Editor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/Text-Editor1.0.0/ && $(COPY_FILE) --parents src/Editor.h src/FileBrowser.h src/FileBrowserView.h src/FileTreeBrowser.h src/MainWindow.h build/Text-Editor1.0.0/ && $(COPY_FILE) --parents resources/resources.qrc build/Text-Editor1.0.0/ && $(COPY_FILE) --parents src/Editor.cpp src/FileBrowser.cpp src/FileBrowserView.cpp src/FileTreeBrowser.cpp src/main.cpp src/MainWindow.cpp build/Text-Editor1.0.0/ && (cd `dirname build/Text-Editor1.0.0` && $(TAR) Text-Editor1.0.0.tar Text-Editor1.0.0 && $(COMPRESS) Text-Editor1.0.0.tar) && $(MOVE) `dirname build/Text-Editor1.0.0`/Text-Editor1.0.0.tar.gz . && $(DEL_FILE) -r build/Text-Editor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_Editor.cpp build/moc_FileBrowser.cpp build/moc_FileBrowserView.cpp build/moc_FileTreeBrowser.cpp build/moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_Editor.cpp build/moc_FileBrowser.cpp build/moc_FileBrowserView.cpp build/moc_FileTreeBrowser.cpp build/moc_MainWindow.cpp
build/moc_Editor.cpp: src/Editor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/Editor.h -o build/moc_Editor.cpp

build/moc_FileBrowser.cpp: src/FileBrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/FileBrowser.h -o build/moc_FileBrowser.cpp

build/moc_FileBrowserView.cpp: src/FileBrowserView.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/FileBrowserView.h -o build/moc_FileBrowserView.cpp

build/moc_FileTreeBrowser.cpp: src/FileTreeBrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/FileTreeBrowser.h -o build/moc_FileTreeBrowser.cpp

build/moc_MainWindow.cpp: src/Editor.h \
		src/FileBrowserView.h \
		src/MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/MainWindow.h -o build/moc_MainWindow.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources/resources.qrc \
		resources/images/qt_logo.png \
		resources/images/paste_icon.png \
		resources/images/file_icon.png \
		resources/images/cut_icon.png \
		resources/images/open_icon.png \
		resources/images/text_doc.png \
		resources/images/dir_icon.png \
		resources/images/save_icon.png \
		resources/images/copy_icon.png \
		resources/images/new_icon.png \
		resources/images/quit_icon.png \
		resources/images/undo_icon.png \
		resources/images/redo_icon.png
	/usr/bin/rcc -name resources resources/resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

build/Editor.o: src/Editor.cpp src/Editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Editor.o src/Editor.cpp

build/FileBrowser.o: src/FileBrowser.cpp src/FileBrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/FileBrowser.o src/FileBrowser.cpp

build/FileBrowserView.o: src/FileBrowserView.cpp src/FileBrowserView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/FileBrowserView.o src/FileBrowserView.cpp

build/FileTreeBrowser.o: src/FileTreeBrowser.cpp src/FileTreeBrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/FileTreeBrowser.o src/FileTreeBrowser.cpp

build/main.o: src/main.cpp src/MainWindow.h \
		src/Editor.h \
		src/FileBrowserView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/MainWindow.o: src/MainWindow.cpp src/MainWindow.h \
		src/Editor.h \
		src/FileBrowserView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainWindow.o src/MainWindow.cpp

build/moc_Editor.o: build/moc_Editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_Editor.o build/moc_Editor.cpp

build/moc_FileBrowser.o: build/moc_FileBrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_FileBrowser.o build/moc_FileBrowser.cpp

build/moc_FileBrowserView.o: build/moc_FileBrowserView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_FileBrowserView.o build/moc_FileBrowserView.cpp

build/moc_FileTreeBrowser.o: build/moc_FileTreeBrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_FileTreeBrowser.o build/moc_FileTreeBrowser.cpp

build/moc_MainWindow.o: build/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MainWindow.o build/moc_MainWindow.cpp

build/qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

