######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 19 18:55:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . resources
INCLUDEPATH += .

# Input
HEADERS += Editor.h FileBrowser.h MainWindow.h
SOURCES += Editor.cpp FileBrowser.cpp main.cpp MainWindow.cpp
RESOURCES += resources/resources.qrc
