######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 28 14:28:42 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Editor.h MainWindow.h
SOURCES += Editor.cpp main.cpp MainWindow.cpp
